use_frameworks!

platform :ios, '8.0'

target 'CFNetworking_Example' do
  pod 'CFNetworking', :path => '../'

  target 'CFNetworking_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
